### ISSUE TITLE
[BUG] ngx-editorjs 3.0.2: Angular Material required

### ISSUE THREAD

**Issue by przemekpobuta** [tanepiper/ngx-tinynodes#10] opened 2019-06-16 09:28 UTC
**Which Library?**
ngx-editorjs 3.0.2

**Describe the bug**
Done "Installing and usage" instruction from README and following error appear:

`ERROR in node_modules/@tinynodes/ngx-editorjs/lib/containers/editorjs-mat-field/editorjs-mat-field.component.d.ts(4,37): error TS2307: Cannot find module
'@angular/material/form-field'.`

**To Reproduce**
Follow README "Installing and usage".

**Expected behavior**
Use ngx-editorjs without Angular Material.

**Comment by tanepiper** [comment] 2019-06-16 13:19
Hi @przemekpobuta - you should now be able to import `NgxEditorJSComponentModule` which is the component minus any Material dependencies.  Thanks for catching this, I'm building mostly for material so I missed this.

**Comment by whyour** [comment] 2019-08-16 10:27
Hi @tanepiper - still has error. Is it imported like this?
`NgxEditorJSComponentModule.forRoot({
        editorjs: {
            autofocus: false,
            holder: 'editor',
            initialBlock: 'paragraph',
            data: {
            time: Date.now(),
            version: '2.15.0',
            blocks: []
            }
        }
    })`
![image](https://user-images.githubusercontent.com/22700758/63161695-44c39e00-c053-11e9-82d3-5f3203fdbb5d.png)

**Comment by tanepiper** [comment] 2019-08-16 14:48
@whyour Thanks for the report, I won't be able to look at it right away I'm afraid but let me find time to test it, hopefully, it's not a regression

**Comment by tanepiper** [comment] 2019-08-16 15:48
@whyour I am not able to reproduce this, importing the `NgxEditorJSComponentModule`.  Do you have some code you can share if you're still having an issue?

**Comment by tanepiper** [comment] 2019-08-23 09:35
Hi @whyour I haven't had a reply in a week so I am closing this ticket.

**Closed as completed by tanepiper** 2019-08-23 09:35 UTC
Labels: bug, investigating
